### ISSUE TITLE
TableView

### ISSUE THREAD

**Issue by NES8** [Planet1107/PNTToolbar#16]
Hi,

I'm using a tableView and my textField are all inside one cell.

**\* Configuring PNTToolbar in UITableViewDataSource class ***

When I touch inside a textField, tableView scrolls to top and (sometimes) return to textField position.

Buttons "Previous" and "Next" works, but some times the app crashes.

Done button works correctly.

**\* Configuring PNTToolbar in UITableViewCell class ***

When I touch inside textField, never scrolls.

Buttons "Previous" and "Next" doesn't work.

Done button works correctly.

Your class is very interesting. Please, can you fix bugs?

Thank you.

**Comment by jcavar** [comment]
Hi, I am not sure what's happening, but I created demo project with table view and one cell inside and I think it's working as expected. It's here http://fly.srk.fer.hr/~jcavar/demo.zip

**Comment by NES8** [comment]
Hi,

Thank you for your answer!

Maybe the problem is my short experience with iOS. I'm using a UIViewController with a UITableViewController inside, using dynamic cells. I have created a demo project too: https://www.dropbox.com/s/h4uz06iluq4rrt2/DemoToolbar.zip

I don't know why, but scroll is a little crazy.

**Comment by jcavar** [comment]
Hello,
Sorry for waiting. It seems that our code was broken. We fixed the bug now. Can you just download and replace PNTToolbar files, and try again your project?

**Comment by jcavar** [comment]
I will close this issue. If there is still problem, please reopen it.
