### ISSUE TITLE
big frame when keyboard disappears

### ISSUE THREAD

**Issue by NES8** [Planet1107/PNTToolbar#17]
Hi,

Thank you for fix the previous issue. I’m trying left five stars feedback on cocoacontrols, but I obtain an error HTTP500 when login :(

I have a new issue! I have a button with this line of code:

[self.view endEditing:YES];

After that, keyboard disappears, but a big frame continues showing.

I have fixed this issue declaring your keyboardWillHide method on PNTToolbar.h and replacing my code with:

[self.inputViewToolbar keyboardWillHide:nil];
[self.view endEditing:YES];

Thanks you.

**Comment by jcavar** [comment]
Hi,
We just fixed your problem, so you don't need to call [self.inputViewToolbar keyboardWillHide:nil];
Can you please download new files and try it?

**Comment by NES8** [comment]
Hi,

Bug fixed. Good job.

Thank you!

**Comment by jcavar** [comment]
Thank you for reporting bugs!
